// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmQAGO-6xxU6TsGSHn0nJcrVDn-J_nlvI',
    appId: '1:254128203598:web:d9a3f6f1ed3c5e80c8e01f',
    messagingSenderId: '254128203598',
    projectId: 'mini-project-c3d2e',
    authDomain: 'mini-project-c3d2e.firebaseapp.com',
    storageBucket: 'mini-project-c3d2e.firebasestorage.app',
    measurementId: 'G-8616SEKVC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzQA0PJZlLIsiHXyYv4__t146cBa0G6LM',
    appId: '1:254128203598:android:02379f0ade2dab16c8e01f',
    messagingSenderId: '254128203598',
    projectId: 'mini-project-c3d2e',
    storageBucket: 'mini-project-c3d2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC34PwGBnWg5e3M75ehnHIvrfUYVxcRalE',
    appId: '1:254128203598:ios:3dcf6d701f5de82cc8e01f',
    messagingSenderId: '254128203598',
    projectId: 'mini-project-c3d2e',
    storageBucket: 'mini-project-c3d2e.firebasestorage.app',
    iosBundleId: 'com.example.laporpak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC34PwGBnWg5e3M75ehnHIvrfUYVxcRalE',
    appId: '1:254128203598:ios:3dcf6d701f5de82cc8e01f',
    messagingSenderId: '254128203598',
    projectId: 'mini-project-c3d2e',
    storageBucket: 'mini-project-c3d2e.firebasestorage.app',
    iosBundleId: 'com.example.laporpak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmQAGO-6xxU6TsGSHn0nJcrVDn-J_nlvI',
    appId: '1:254128203598:web:354c087300dc41bdc8e01f',
    messagingSenderId: '254128203598',
    projectId: 'mini-project-c3d2e',
    authDomain: 'mini-project-c3d2e.firebaseapp.com',
    storageBucket: 'mini-project-c3d2e.firebasestorage.app',
    measurementId: 'G-LW0L9FGWR7',
  );

}